name: 💡 Feature request
description: Create a report for a new feature request
title: "💡 [Feature request]: "
labels: ["feature request"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: To rule out invalid issues, confirm and check each one of the checkboxes.
      options:
        - label: This is not a [support issue or a question](https://github.com/airdcpp/airdcpp-windows/discussions)
          required: true
        - label: I performed a [cursory search of the issue tracker](https://github.com/airdcpp/airdcpp-windows/issues) to avoid opening a duplicate issue
          required: true

  - type: textarea
    attributes:
      label: Describe the issue
      description: |
        Be as clear as possible. Nobody can read mind and nobody is looking at your issue over your shoulder.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        Tell us what should happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behavior
      description: |
        Tell us what happens instead.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshot(s)
      description: |
        Add screenshot(s) to describe visual issues. 
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional information
      description: |
        You can provide additional information here to make it easier to understand your issue.
    validations:
      required: false
