name: Bug report
description: Create a report to help us improve
title: "[Bug]: <title>"
labels: ["bug", "needs triage"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: To rule out invalid issues, confirm and check each one of the checkboxes.
      options:
        - label: This is not a [support issue or a question](https://github.com/airdcpp/airdcpp-windows/discussions)
          required: true
        - label: I performed a [cursory search of the issue tracker](https://github.com/airdcpp/airdcpp-windows/issues) to avoid opening a duplicate issue
          required: true
        - label: I am running the latest version of AirDC++
          required: true

  - type: markdown
    attributes:
      value: |
        ![version]https://img.shields.io/github/release/airdcpp/airgit.svg?label=version&maxAge=3600

  - type: textarea
    attributes:
      label: Describe the issue
      description: |
        Be as clear as possible. Nobody can read mind and nobody is looking at your issue over your shoulder.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        Tell us what should happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behavior
      description: |
        Tell us what happens instead.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce the behavior if needed
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshot(s)
      description: |
        Add screenshot(s) to describe visual issues. 
    validations:
      required: false

  - type: textarea
    attributes:
      label: Crash log
      description: |
        When AirDC++ crash it will sometimes create an `exceptioninfo.txt`. Open it and verify it is the correct date and time of the crash.
        If your client won't create any exceptioninfo.txt you can read more [here](https://github.com/Sopor/airdcpp-windows/wiki/Client-hangs-(deadlock)#getting-information-from-a-frozen-or-hung-client) how to get information out of a frozen client.
      placeholder: Paste all text from exceptioninfo.txt here or from WinDbg
      render: shell
    validations:
      required: false

  - type: input
    attributes:
      label: AirDC++ version and architecture (x86 or x64)
      placeholder: e.g. 4.11 x64
    validations:
      required: true

  - type: input
    attributes:
      label: Operating System name, version and architecture
      placeholder: e.g. Windows 10 21H2 x64
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: |
        You can provide additional information here to make it easier to understand your problem.
    validations:
      required: false
