blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://github.com/airdcpp/airdcpp-windows
    about: Answers to questions and other kinds of help support
  - name: AirDC++ issues
    url: https://github.com/airdcpp/airdcpp-windows
    about: Issues about AirDC++
